;* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
;*              MODIFICAÇÕES PARA USO COM 12F675                   *
;*                FEITAS PELO PROF. MARDSON                        *
;*                     JULHOO DE 2024                              *
;*                 BASEADO NO EXEMPLO DO LIVRO                     *
;*           Desbravando o PIC. David José de Souza                *
;*-----------------------------------------------------------------*
;*   MODELO PARA O PIC 16F628a                                      
;* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; 
;   NESSE PROGRAMA PARA CADA TENSÃO APLICADA, O PIC DEVE RETORNAR EM
;   RB0, RB1 E RB2 OS BITS EQUIVALENTES A B0, B1 E B2 PARA UM DISPLAY DE 7 SEGMENTOS COMUM
;   SENDO O RB0 O BIT MENOS SIGNIFICATIVO E RB2 O BIT MAIS SIGNIFICATIVO
;   PARA A TENSAO ESPECIFICADA DE 0,35V O VALOR MAIS PROXIMO POSSIVEL FOI DE 0,42V
;   PARA 0,7 A MAIS PROXIMA EH 0,62V
    
;*                     ARQUIVOS DE DEFINIÇÕES                      *

#include "p16f628a.inc"

; CONFIG
; __config 0xFFFF
 __CONFIG _FOSC_EXTRCCLK & _WDTE_ON & _PWRTE_OFF & _MCLRE_ON & _BOREN_ON & _LVP_ON & _CPD_OFF & _CP_OFF

#DEFINE	BANK0	BCF STATUS,RP0	;SETA BANK 0 DE MEMÓRIA
#DEFINE	BANK1	BSF STATUS,RP0	;SETA BANK 1 DE MAMÓRIA

;*                         VARIÁVEIS                               *

	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE
					;USUÁRIO
		W_TEMP		;REGISTRADORES TEMPORÁRIOS PARA USO
		STATUS_TEMP	;JUNTO ÀS INTERRUPÇÕES

		;COLOQUE AQUI SUAS NOVAS VARIÁVEIS
		;NÃO ESQUEÇA COMENTÁRIOS ESCLARECEDORES

	ENDC			;FIM DO BLOCO DE DEFINIÇÃO DE VARIÁVEIS

;*                        FLAGS INTERNOS                           *

;*                         CONSTANTES                              *

;*                           ENTRADAS                              *

;*                           SAÍDAS                                *

;*                       VETOR DE RESET                            *

	ORG	0x00			;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
;*                    INÍCIO DA INTERRUPÇÃO                        *

	ORG	0x04			;ENDEREÇO INICIAL DA INTERRUPÇÃO
	MOVWF	W_TEMP		;COPIA W PARA W_TEMP
	SWAPF	STATUS,W
	MOVWF	STATUS_TEMP	;COPIA STATUS PARA STATUS_TEMP

;*                    ROTINA DE INTERRUPÇÃO                        *

;*                 ROTINA DE SAÍDA DA INTERRUPÇÃO                  *

SAI_INT
	SWAPF	STATUS_TEMP,W
	MOVWF	STATUS		;MOVE STATUS_TEMP PARA STATUS
	SWAPF	W_TEMP,F
	SWAPF	W_TEMP,W	;MOVE W_TEMP PARA W
	RETFIE

;*	            	 ROTINAS E SUBROTINAS                      *

SUBROTINA1

	;CORPO DA ROTINA

	RETURN
SAIDA000:
    BCF PORTB, RB0
    BCF	PORTB, RB1
    BCF	PORTB, RB2
    BCF PORTB, RB3
    GOTO LOOP

SAIDA001:
    BSF PORTB, 0
    BCF PORTB, 1
    BCF PORTB, 2
    BCF PORTB, RB3
    GOTO LOOP

SAIDA010:
    BCF PORTB, 0
    BSF PORTB, 1
    BCF PORTB, 2
    BCF PORTB, RB3
    GOTO LOOP
    

SAIDA011:
    BSF PORTB, 0
    BSF PORTB, 1
    BCF PORTB, 2
    BCF PORTB, RB3
    GOTO LOOP

    
SAIDA100:
    BCF PORTB, 0
    BCF PORTB, 1
    BSF PORTB, 2
    BCF PORTB, RB3
    GOTO LOOP

    
SAIDA101:
    BSF PORTB, 0
    BCF PORTB, 1
    BSF PORTB, 2
    BCF PORTB, RB3
    GOTO LOOP

SAIDA110:
    BCF PORTB, 0
    BSF PORTB, 1
    BSF PORTB, 2
    BCF PORTB, RB3
    GOTO LOOP

SAIDA111:
    BSF PORTB, 0
    BSF PORTB, 1
    BSF PORTB, 2
    BCF PORTB, RB3
    GOTO LOOP
    
SAIDA1000:
    BCF PORTB, RB0
    BCF PORTB, RB1
    BCF PORTB, RB2
    BSF PORTB, RB3
    GOTO LOOP
 
SAIDA1001:
    BSF PORTB, RB0
    BCF	PORTB, RB1
    BCF	PORTB, RB2
    BSF PORTB, RB3
    GOTO LOOP
    
TESTE_001_OU_MAIOR:
    ;AGORA EH A HORA DE TESTAR SE O MEU VIN É MAIOR OU MENOR QUE 0,7
    BANK1
    MOVLW   B'10100011'
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA001
    GOTO    TESTE_010_OU_MAIOR

TESTE_010_OU_MAIOR:
    ;AGORA EH A HORA DE TESTAR SE O MEU VIN É MAIOR OU MENOR QUE 1,05
    BANK1
    MOVLW   B'10100101'
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA010
    GOTO    TESTE_011_OU_MAIOR
 
TESTE_011_OU_MAIOR:
    ;AGORA EH A HORA DE TESTAR SE O MEU VIN É MAIOR OU MENOR QUE 1,05
    BANK1
    MOVLW   B'10000001'		;MUDEI PRA HIGH PARA OBTER UMA MAIOR PRECISAO
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA011
    GOTO    TESTE_100_OU_MAIOR
   
TESTE_100_OU_MAIOR:		;OUTPUT = D'4'?
    BANK1
    MOVLW   B'10000011'		;HIGH - D'3'
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA100
    GOTO    TESTE_101_OU_MAIOR

TESTE_101_OU_MAIOR:		;OUTPUT = D'5'?
    BANK1
    MOVLW   B'10101010'		;LOW - D'10'
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA101
    GOTO    TESTE_110_OU_MAIOR

TESTE_110_OU_MAIOR:
    BANK1
    MOVLW   B'10101100'		;LOW - D'12		
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA110
    GOTO    TESTE_111_OU_MAIOR
 
TESTE_111_OU_MAIOR:
    BANK1
    MOVLW   B'10001011'		;HIGH D'11'		
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA111
    GOTO    TESTE_1000_OU_1001
    
TESTE_1000_OU_1001:	;8 -> VIN < 3.2 : 9 -> VIN > 3.2
    BANK1
    MOVLW   B'10101111'		;LOW D'15'		
    MOVWF   VRCON
    BANK0
    BTFSC   CMCON, 6
    GOTO    SAIDA1000
    GOTO    SAIDA1001


    
;*                     INICIO DO PROGRAMA                          *
	
INICIO
	BANK1			; ALTERA PARA O BANCO 1  
	MOVLW	B'00000001'
	MOVWF	TRISA
	MOVLW	B'00000000'	; CONFIGURA TODAS AS PORTAS DO GPIO (PINOS)
	MOVWF	TRISB		; COMO SAÍDAS, AQUI USAMOS TRISB PARA PORTB
	MOVLW	B'00000100'	; CONFIGURAÇÃO PARA OPTION_REG
	MOVWF	OPTION_REG	; DEFINE OPÇÕES DE OPERAÇÃO
	MOVLW	B'00000000'
	MOVWF	INTCON		; DESABILITA AS INTERRUPÇÕES
;LOW: VREF = 5X/24
;HIGH: VREF = 5*((1/4)+X/32)
	
	MOVLW	B'10100010'
	MOVWF	VRCON		; PASSEI 5/24 PARA O VRCON =  0,21
	
	BANK0				; RETORNA PARA O BANCO 0
	MOVLW	B'00000010'
	MOVWF	CMCON
;   B7 - C2 OUT
;   B6 - C1 OUT
;   B5 - INVC2
;   B4 - INVC1 
;   B3 ? 0(C1 VIN- CONNECTS TO RA0): 1(C1 VIN- CONNECTS TO RA0)
;   B0 A B2 - ESCOLHER O COMPARADOR
;   EU ESCOLHI O QUE USA O VREF E O AN0 

;*                     INICIALIZAÇÃO DAS VARIÁVEIS                 *

;*                     ROTINA PRINCIPAL                            *

MAIN
	; CMCON (NÃO INVERTIDO) OUTPUT? 0(VIN+>VIN-): 1(VIN+<VIN-)
	; VIN+ = VREF / VIN- = AN0
	; AN0 > VREF --> COUT = 1
	; PULA LINHA SE O AN0 > VREF
	BTFSC	CMCON, 6
	GOTO	SAIDA000
	GOTO	TESTE_001_OU_MAIOR
	
	GOTO	MAIN
LOOP
	GOTO	LOOP
	END