;*                     ARQUIVOS DE DEFINIÇÕES                      *
#INCLUDE <p12f675.inc>	;ARQUIVO PADRÃO MICROCHIP PARA 12F675
; 
	
__CONFIG _BODEN_OFF & _CP_OFF & _PWRTE_ON & _WDT_OFF & _MCLRE_OFF & _INTRC_OSC_NOCLKOUT
;*                    PAGINAÇÃO DE MEMÓRIA                         *
#DEFINE	BANK0	BCF STATUS,RP0	;SETA BANK 0 DE MEMÓRIA
#DEFINE	BANK1	BSF STATUS,RP0	;SETA BANK 1 DE MAMÓRIA

;*                         REGISTRADORES DE USO GERAL

	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE
					;USUÁRIO
		W_TEMP		;REGISTRADORES TEMPORÁRIOS PARA USO
		STATUS_TEMP	;JUNTO ÀS INTERRUPÇÕES
		ENTRADA

		;COLOQUE AQUI SUAS NOVAS VARIÁVEIS
		;NÃO ESQUEÇA COMENTÁRIOS ESCLARECEDORES

	ENDC			;FIM DO BLOCO DE DEFINIÇÃO DE VARIÁVEIS

;*                        FLAGS INTERNOS                           *

;*                         CONSTANTES                              *

;*                           ENTRADAS                              *
#DEFINE VIN GP1

;*                           SAÍDAS                                *
#DEFINE	B0 GP0
#DEFINE	B1 GP2
#DEFINE	B2 GP4
	
;*                       VETOR DE RESET                            *

	ORG	0x00			;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
;*                    INÍCIO DA INTERRUPÇÃO                        *

	ORG	0x04			;ENDEREÇO INICIAL DA INTERRUPÇÃO
	MOVWF	W_TEMP		;COPIA W PARA W_TEMP
	SWAPF	STATUS,W
	MOVWF	STATUS_TEMP	;COPIA STATUS PARA STATUS_TEMP

;*                    ROTINA DE INTERRUPÇÃO                        *

;*                 ROTINA DE SAÍDA DA INTERRUPÇÃO                  *

SAI_INT
	SWAPF	STATUS_TEMP,W
	MOVWF	STATUS		;MOVE STATUS_TEMP PARA STATUS
	SWAPF	W_TEMP,F
	SWAPF	W_TEMP,W	;MOVE W_TEMP PARA W
	RETFIE

;*	            	 ROTINAS E SUBROTINAS                      *

SUBROTINA1

	;CORPO DA ROTINA

	RETURN

LIGA000:
    BCF GPIO, B0
    BCF GPIO, B1
    BCF GPIO, B2 ; VOU MANDAR 000 PARA MEU DISPLAY DE  7 SEGMENTOS
    
    GOTO LOOP


TESTE1:
    BANK1		;CHAVEAR PQ VRCON É NO BANCO 1
    MOVLW   B'10100101'	    ;Vin = 1V
    MOVWF   VRCON
    BANK0
    BTFSS   CMCON, 6	;SE VIN>VREF VAI PARA TESTE2		
    GOTO    LIGA001
    GOTO    TESTE2

TESTE2:
    BANK1
    MOVLW B'10100111'
    MOVWF VRCON  ;5*5/24 = 1.04(será o meu Vref  a  ser comparado com meu Vin(GP5)
    BANK0
    
    BTFSS CMCON, 6
    GOTO LIGA010
    GOTO TESTE3

    
LIGA001:
    BSF GPIO, B0
    BCF GPIO, B1
    BCF GPIO, B2 ; VOU MANDAR 001 PARA MEU DISPLAY DE  7 SEGMENTOS
    GOTO LOOP

TESTE3
    BANK1
    MOVLW B'10100111'
    MOVWF VRCON  ;7*5/24 = 1.45(será o meu Vref  a  ser comparado com meu Vin(GP5)
    BANK0
    BTFSS CMCON, 6
    CALL LIGA010
    CALL TESTE4
    
    
LIGA010:
    BCF	    GPIO, B0
    BSF	    GPIO, B1
    BCF	    GPIO, B2 ; VOU MANDAR 001 PARA MEU DISPLAY DE  7 SEGMENTOS
    GOTO    LOOP

TESTE4:
    BANK1
    MOVLW   B'10101010'
    MOVWF   VRCON  
    BANK0
    
    BTFSS   CMCON, 6
    CALL    LIGA011
    CALL    TESTE5
    
LIGA011:
    BSF	   GPIO, B0
    BSF	   GPIO, B1
    BCF	   GPIO, B2
    GOTO   LOOP
    
TESTE5:
    BANK1
    MOVLW   B'10101100'
    MOVWF   VRCON  
    BANK0
    
    BTFSS   CMCON, 6
    CALL    LIGA100
    CALL    TESTE6
    
LIGA100:
    BCF	   GPIO, B0
    BCF	   GPIO, B1
    BSF	   GPIO, B2
    GOTO   LOOP
    
TESTE6:
    BANK1
    MOVLW   B'10101111'
    MOVWF   VRCON  
    BANK0
    
    BTFSS   CMCON, 6
    CALL    LIGA101
    CALL    TESTE7

LIGA101:
    BSF	    GPIO, B0
    BCF	    GPIO, B1
    BSF	    GPIO, B2
    GOTO    LOOP
    
TESTE7:
    BANK1
    MOVLW   B'10001110'	;HIGH RANGE
    MOVWF   VRCON  
    BANK0
    
    BTFSS   CMCON, 6
    CALL    LIGA110
    CALL    LIGA111
    
LIGA110:
    BCF	    GPIO, B0
    BSF	    GPIO, B1
    BSF	    GPIO, B2
    GOTO    LOOP

LIGA111:
    BSF	    GPIO, B0
    BSF	    GPIO, B1
    BSF	    GPIO, B2
    GOTO    LOOP
    
;*                     INICIO DO PROGRAMA                          *

INICIO
	BANK1				;ALTERA PARA O BANCO 1
	MOVLW	B'00000010'	;GP1(VIN) É ENTRADA
	MOVWF	TRISIO		
	MOVLW	B'00000010'
	MOVWF	ANSEL		;GP1(VIN) É ANALÓGICA
	CLRF	OPTION_REG	;DEFINE OPÇÕES DE OPERAÇÃO
	CLRF	INTCON		;DESABILITA INTERRUPÇÕES
	
	;VRCON É O REGISTRADOR QUE VAI DIZER QUAL É A TENSÃO A SER COMPARADA
	;COM O MEU VIN
	;EU PRECISO DE UM VALOR PRÓXIMO A 0,5V
	; LOW RANGE(BIT5 = 1)(x*0.208)
	; 0000 -> VREF = (0/24)*5 = 0
	; 0001 -> VREF = 5/24 = 0.2
	; 0010 -> VREF = 0,4(VOU ESCOLHER ESSE)
	; 0011 -> VREF = 0.6
	; 0100 -> VREF = 0,8
	; 0101 -> VREF = 1
	; 0110
	; 0111 -> VREF = 1.5
	
	
	
	; HIGH RANGE(BIT5 = 0) COMEÇA A PARTIR DE 1,25
	; 0000 -> VREF = 1.25+(0)*0.15625 
	MOVLW	B'10100010'
	MOVWF	VRCON		;CONFIGURA A TENSÃO DE REFERÊNCIA INTERNA

	BANK0				;RETORNA PARA O BANCO
	MOVLW	B'00010100'     ;COMPARADOR COM SAÍDA E REFERÊNCIA INTERNA
	;EU INVERTI AS ENTRADAS PARA FAVORECER A LÓGICA
	MOVWF	CMCON		;DEFINE O MODO DE OPERAÇÃO DO COMPARADOR ANALÓGICO	
	
;*                     INICIALIZAÇÃO DAS VARIÁVEIS                 *
	CLRF	GPIO
;*                     ROTINA PRINCIPAL                            *

;AQUI TEM UM BREAKPOINT PARA SETAR O VIN
MAIN
	BTFSS	CMCON, 6    ;COUT = 1 (GP1>VREF)
	CALL	LIGA000	    ;SUBROTINA PARA MANDAR 000 PARA AS SAÍDAS 
	CALL	TESTE1	    ;SUBROTINA PARA TESTAR SE O VIN ESTÁ ENTRE 0,5 E 1
	
	GOTO	MAIN
LOOP
	GOTO	LOOP
	END
