;*   MODELO PARA O PIC 12F675                                      *
;* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
; gp0 = Vin
; comparar gp0 com gp1
	; Se gp0 > 
	;    gp5 = 1
	; senão
	;    gp5 = 0
;*                     ARQUIVOS DE DEFINIÇÕES                      *
#INCLUDE <p12f675.inc>	;ARQUIVO PADRÃO MICROCHIP PARA 12F675

	__CONFIG _BODEN_OFF & _CP_OFF & _PWRTE_ON & _WDT_OFF & _MCLRE_ON & _INTRC_OSC_NOCLKOUT

;*                    PAGINAÇÃO DE MEMÓRIA                         *
#DEFINE	BANK0	BCF STATUS,RP0	;SETA BANK 0 DE MEMÓRIA
#DEFINE	BANK1	BSF STATUS,RP0	;SETA BANK 1 DE MAMÓRIA


;*                         VARIÁVEIS                               *


	CBLOCK	0x20	;ENDEREÇO INICIAL DA MEMÓRIA DE
					;USUÁRIO
		W_TEMP		;REGISTRADORES TEMPORÁRIOS PARA USO
		STATUS_TEMP	;JUNTO ÀS INTERRUPÇÕES

	ENDC			;FIM DO BLOCO DE DEFINIÇÃO DE VARIÁVEIS

;*                       VETOR DE RESET                            *

	ORG	0x00			;ENDEREÇO INICIAL DE PROCESSAMENTO
	GOTO	INICIO
	
;*                    INÍCIO DA INTERRUPÇÃO                        *

	ORG	0x04			;ENDEREÇO INICIAL DA INTERRUPÇÃO
	MOVWF	W_TEMP		;COPIA W PARA W_TEMP
	SWAPF	STATUS,W
	MOVWF	STATUS_TEMP	;COPIA STATUS PARA STATUS_TEMP

;*                    ROTINA DE INTERRUPÇÃO                        *

	BTFSS   PIR1, 3 ; Verifica se o bit CMIF(3) está setado
	GOTO SAI_INT   ;PULA ESSE COMANDO SE A INTERRUPÇÃO TIVER ACONTECIDO PELO COMPARADOR
	;SE A INTERRUPÇÃO TIVER ACONTECIDO POR MEIO DO COMPARADOR
	BTFSC	CMCON, 6    ;COUT(6)
	GOTO ACENDE_LED	    ;SE GP0>GP1 -> ACENDE LED EM GP5
	GOTO APAGA_LED
	

;*                 ROTINA DE SAÍDA DA INTERRUPÇÃO                  *

SAI_INT
	BCF PIR1, 3 ;LIMPA FLAG
	SWAPF	STATUS_TEMP,W
	MOVWF	STATUS		;MOVE STATUS_TEMP PARA STATUS
	SWAPF	W_TEMP,F
	SWAPF	W_TEMP,W	;MOVE W_TEMP PARA W
	
	RETFIE


SUBROTINA1

	;CORPO DA ROTINA

	RETURN
	
ACENDE_LED
    BSF GPIO, GP5
    GOTO LOOP	;SE NÃO VOLTA PRA MAIN

APAGA_LED
    BCF GPIO, GP5
    GOTO LOOP	;SE NÃO VOLTA PRA MAIN

	
INICIO
	BANK1				;ALTERA PARA O BANCO 1
	MOVLW	B'00000011' ;CONFIGURA TODAS AS PORTAS DO GPIO (PINOS)
	MOVWF	TRISIO		;COMO SAÍDAS
	MOVLW	B'00000011'
	MOVWF	ANSEL 		;DEFINE PORTAS COMO Digital I/O
	MOVLW	B'00000100'
	MOVWF	OPTION_REG	;DEFINE OPÇÕES DE OPERAÇÃO
	MOVLW	B'00000000'
	MOVWF	INTCON		;DEFINE OPÇÕES DE INTERRUPÇÕES
	MOVLW	B'00000000'
	MOVWF	PIE1
	
	BANK0				;RETORNA PARA O BANCO
	MOVLW	B'00000010'
	MOVWF	CMCON		;DEFINE O MODO DE OPERAÇÃO DO COMPARADOR ANALÓGICO
	;MOVLW	B''
	;MOVWF	PIR1

;*                     ROTINA PRINCIPAL                            
MAIN
	BTFSC	CMCON, 6    ;COUT = 1 SE GP1>GP0
			    ;COUT = 0 SE GP1<GP1
	CALL ACENDE_LED
	CALL APAGA_LED
	LOOP
	

	
	GOTO	MAIN


	END
